Update peerDependencies to include React 18
beamworks/react-csv-importer pull request #75
Opened 2022-04-13 14:19 UTC by timarney

Running into  dependency issues when using React 18

<img width="620" alt="Screen Shot 2022-04-13 at 10 17 10 AM" src="https://user-images.githubusercontent.com/62242/163201295-06e1bf91-5796-4f5f-89b3-279abdfc7b89.png">

If I force install importing is working as expected.

2022-04-15 22:23 UTC, unframework requested changes
Hi Tim, thanks for fixing this. I suggested a couple tweaks to ensure that projects with React v17 are not affected, please see review comments. Thanks!

2022-04-15 22:23 UTC, unframework commented on package.json
> +    "react": "^16.8.0 || ^18.0.0",
```suggestion
    "react": "^16.8.0 || >=17.0.0",
```

2022-04-15 22:23 UTC, unframework commented on package.json
> +    "react-dom": "^16.8.0 || ^18.0.0"
```suggestion
    "react-dom": "^16.8.0 || >=17.0.0"
```

2022-04-16 10:06 UTC, timarney commented
Perfect that makes sense.

2022-04-21 02:02 UTC, unframework approved these changes

2022-04-21 02:02 UTC, merged

2022-04-21 02:32 UTC, unframework commented
Hi Tim, I just published this in v0.7.1, let me know if there are any issues, thanks again for contributing!